<a href="https://colab.research.google.com/github/ravitejabankupalli/python-daily-notebooks/blob/main/Day_6_Python_For_AIML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this note book we are going to learn Python for AIML. The Topics for today are as follows:
- Understand how ML code:
    - combines values
    - summarizes data
    - prepares inputs for models

In [3]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [10 20 30 40]


In [4]:
a+b

array([11, 22, 33, 44])

In [5]:
b-a

array([ 9, 18, 27, 36])

In [6]:
a*b

array([ 10,  40,  90, 160])

In [7]:
b/a

array([10., 10., 10., 10.])

In [8]:
a+5

array([6, 7, 8, 9])

In [9]:
a*2

array([2, 4, 6, 8])

In [10]:
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [10 20 30 40]


In [11]:
c=np.array(
    [
        [1,2],
        [3,4]
    ]
)
c

array([[1, 2],
       [3, 4]])

In [12]:
c*2

array([[2, 4],
       [6, 8]])

In [14]:
x = np.array([2, 4, 6])
y = np.array([1, 3, 5])
print("x =",x)
print("Y =",y)

x = [2 4 6]
Y = [1 3 5]


In [15]:
x+y

array([ 3,  7, 11])

In [16]:
x-y

array([1, 1, 1])

In [17]:
x*y

array([ 2, 12, 30])

In [21]:
x*2
# This is Broadcasting
# x*2 = [2,4,6]*[2,2,2] (Here it is broadcating 2 into suatable matrix shape to multiply the values)

array([ 4,  8, 12])

In [22]:
x/y

array([2.        , 1.33333333, 1.2       ])

Element-wise operations:
- NumPy applies operations per element
- No loops → fast and scalable
- Core building block of ML computations

In [23]:
import numpy as np

a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print("a = ", a)

a =  [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [25]:
print(a.sum())

450


In [26]:
print(a.sum(axis=0))

[120 150 180]


In [27]:
print(a.sum(axis=1))

[ 60 150 240]


In [28]:
print(a.mean())

50.0


In [29]:
print(a.mean(axis=0))

[40. 50. 60.]


In [30]:
print(a.mean(axis=1))

[20. 50. 80.]


In [31]:
print(a.std())

25.81988897471611


In [32]:
print(a.std(axis=0))

[24.49489743 24.49489743 24.49489743]


In [33]:
print(a.std(axis=1))

[8.16496581 8.16496581 8.16496581]


In [34]:
print((a-a.mean())/a.std())

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


Aggregations:
- sum, mean, std summarize data
- axis controls feature-wise vs sample-wise aggregation
- mean and std are critical for normalization

### Now these are very important topics:

- **gradient descent**

- **stable training**

- **faster convergence**

In [36]:
import numpy as np

x = np.array([
    [1, 200],
    [2, 300],
    [3, 400]
])


In [37]:
mean=x.mean(axis=0)
standard_div=x.std(axis=0)
print("mean",mean)
print("standard_div",standard_div)

mean [  2. 300.]
standard_div [ 0.81649658 81.64965809]


In [38]:
x_norm=(x-mean)/standard_div
print(x_norm)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [40]:
#🧠 What just happened?

#Each feature now has:

#mean ≈ 0

#std ≈ 1

# This is standardization.

Normalization:
- rescales features to similar ranges
- improves training stability
- uses mean and standard deviation
- critical for gradient-based models


### Why do we normalize data?
**To center features around zero and scale them to comparable ranges so that optimization is stable and no feature dominates learning due to scale alone.**