<a href="https://colab.research.google.com/github/ravitejabankupalli/python-daily-notebooks/blob/main/Day_5_Python_For_AIML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this note book we are going to learn Python for AIML. The Topics for today are as follows:

2D NumPy arrays

shape, ndim

reshape

row & column indexing

slicing

All ML models ultimately work on tables of numbers:

*   rows = data points
*   columns = features

In [2]:
#lets create a 2D array
import numpy as np
arr=np.array([
    [1,2,3],
    [4,5,6]
])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr.shape

(2, 3)

In [7]:
arr.ndim

2

In [8]:
#Accessing elements in 2d array
arr[0]

array([1, 2, 3])

In [12]:
print(arr[0,1])

2


In [13]:
print(arr[1,1])

5


2D NumPy arrays:
- Represent tabular data
- shape = (rows, columns)
- rows are samples, columns are features


Why reshape exists (intuition first)

Often you receive data as:

a flat list

a CSV column

a stream of numbers

But models expect:

rows = samples

columns = features

reshape enforces structure without changing data.

In [15]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [17]:
a.shape

(6,)

In [18]:
x=a.reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
#one of the golden rule of reshaping is all the elements in the original array and the reshaped array must be same and should have exact same count
#if we try to reshape it to a irregular shape then it throws an error
a=np.array([1,2,3,4,5,6])
print(a)
a.reshape(3,3)

[1 2 3 4 5 6]


ValueError: cannot reshape array of size 6 into shape (3,3)

Automatic dimension inference

it uses -1 as reshaping parameter like (2,-1) or (-1,3) where we are asking it to determine the shape accordingly

In [20]:
a.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

Reshape:
- Changes array structure, not data
- Total elements must match
- -1 lets NumPy infer dimensions
- Shape correctness is critical in ML


In [25]:
import numpy as np

x = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])


In [26]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [32]:
#we all know normal indexing like as shown below
print(x[0])

[10 20 30]


In [33]:
print(x[1,2])

60


In [39]:
##There is a way to access the entire column as shown below

print(x[0,:])

# What we are saying here is x[0th row, starting column: ending column]
# The actual way is x[Starting Row:Ending Row(Excluded), starting column: ending column(Excluded)]

#This is used for:

#feature selection

#normalization

#statistics

[10 20 30]


In [40]:
x[0:2,0:3]

array([[10, 20, 30],
       [40, 50, 60]])

In [41]:
## using this way we can modify the values as well
x[0,2]=1000

In [43]:
x

array([[  10,   20, 1000],
       [  40,   50,   60],
       [  70,   80,   90]])

Indexing:
- X[row] → one sample
- X[:, col] → one feature
- X[row, col] → single value
- Slicing enables feature/sample selection


In [44]:
x

array([[  10,   20, 1000],
       [  40,   50,   60],
       [  70,   80,   90]])

In [46]:
## Lets discuss about axis
## Axis tells numpy to select a direction to apply a functiomn or to do anything
print(np.sum(x[1])) # it adds all the values in 2nd row of the x matrix

150


In [49]:
## Now lets change the axis
print(np.sum(x,axis=0)) # NumPy goes down the rows, Sums each column, Result = one value per feature

[ 120  150 1150]


In [51]:
print(np.sum(x,axis=1))

[1030  150  240]


In [55]:
# One of the important usecases of "axis" is as shown
print("Row wise 1st elements mean: ",x.mean(axis=0))
print("Column wise 1st elements mean: ",x.mean(axis=1))

Row wise 1st elements mean:  [ 40.          50.         383.33333333]
Column wise 1st elements mean:  [343.33333333  50.          80.        ]


- axis = direction you collapse
- axis=0 → rows collapse → feature-wise result
- axis=1 → columns collapse → sample-wise result

Axis concept:
- rows = samples, columns = features
- axis=0 → operate column-wise
- axis=1 → operate row-wise
- Wrong axis leads to silent ML bugs


Day 5 Summary:
- 2D arrays represent ML datasets
- reshape enforces correct structure
- indexing enables sample/feature access
- axis controls row-wise vs column-wise computation
