<a href="https://colab.research.google.com/github/ravitejabankupalli/python-daily-notebooks/blob/main/Day_4_Python_For_AIML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this note book we are going to learn Python for AIML. The Topics for today are as follows:
* NumPy arrays
* Basic operations

In [1]:
a=[1,2,3]
b=[4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

AIML is very high in math, normal lists are not that efficient to handel math like that.

That's why numpy is there

Python lists store pointers to objects

Each operation involves Python-level loops

NumPy uses C-level optimized loops

That’s why NumPy is fast.

Why NumPy:
- Python lists do not support element-wise math
- Lists are slow for large numerical operations
- NumPy provides fast, vectorized computation

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
type(arr)
#This is not a regular python array.

numpy.ndarray

In [8]:
arr+10

array([11, 12, 13])

In [9]:
arr*2

array([2, 4, 6])

In [11]:
lst=[1,2,3]
print(lst+lst) # Normal Python Array
print(arr+arr) #Numpy array

[1, 2, 3, 1, 2, 3]
[2 4 6]


NumPy arrays:
- store homogeneous numeric data
- support vectorized operations
- are the foundation of ML and DL

In [12]:
import numpy as np

arr = np.array([10, 20, 30, 40])

In [13]:
arr

array([10, 20, 30, 40])

In [14]:
arr.shape

(4,)

In [15]:
arr.ndim

1

In [16]:
arr.size

4

In [17]:
arr.dtype

dtype('int64')

In [18]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')

In [20]:
arr3 = np.array([1, 2.5, 3])
arr3.dtype
#NumPy upcasts to maintain uniformity.

dtype('float64')

Array properties:
- shape shows structure
- ndim shows number of dimensions
- size is total elements
- dtype ensures uniform data type

In [21]:
import numpy as np

arr = np.array([10, 20, 30, 40])

In [22]:
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(4,)
1
4
int64


In [26]:
zeros_array=np.zeros([2,2],int)
zeros_array

array([[0, 0],
       [0, 0]])

In [27]:
zeros_array=np.zeros(5)

In [28]:
zeros_array

array([0., 0., 0., 0., 0.])

In [29]:
one_arr=np.ones(5)

In [30]:
one_arr

array([1., 1., 1., 1., 1.])

In [32]:
one_arr=np.ones([5,2,3],int)
one_arr

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [33]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [36]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Creating arrays:
- zeros() and ones() for initialization
- arange() for step-based ranges
- linspace() for evenly spaced values


In [37]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [39]:
print(arr[0])     # first element
print(arr[1])
print(arr[-1])    # last element

10
20
50


In [40]:
arr[1:4]

array([20, 30, 40])

In [41]:
arr[:3]

array([10, 20, 30])

In [42]:
arr[2:]     # from index 2 to end

array([30, 40, 50])

In [43]:
arr[0] = 100
arr

array([100,  20,  30,  40,  50])

# NumPy arrays are mutable, just like lists.

Indexing & slicing:
- NumPy indexing works like lists
- Slicing uses start:end (end not included)
- Arrays are mutable and can be modified in-place

Day 4 Summary:
- Python lists are not suitable for numerical computing
- NumPy arrays enable fast, element-wise operations
- Array properties help understand data structure
- NumPy provides efficient array creation and slicing